server:
    bind:
        host: 0.0.0.0
        port: 80
    url: https://apitestbed.geonovum.nl/joins_pygeoapi
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    cors: true
    pretty_print: true
    admin: false
    limits:
        default_items: 10
        max_items: 50
    # templates: /path/to/templates
    map:
        url: https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/standaard/EPSG:3857/{z}/{x}/{y}.png
        attribution: 'Map data &copy; <a href="https://pdok.nl">PDOK Kadaster</a>'
    joins:
        source_dir: /joins
        max_files: 5

logging:
    level: WARNING

metadata:
    identification:
        title: Geonovum OGC API Testbed
        description: pygeoapi demo instance showcasing OGC API - Joins
        keywords:
            - geospatial
            - data
            - INSPIRE
            - download service
            - joins
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/1adacbe0-93de-46db-be3b-04601bdd1327
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: PDOK / NGR
        url: https://www.pdok.nl/support
    contact:
        name: Centraal Bureau voor de Statistiek (CBS)
        position: Info Service
        address: Henri Faasdreef 312, Postbus 24500
        city: Den Haag
        stateorprovince: Zuid Holland
        postalcode: 2490HA
        country: The Netherlands
        phone: 0031 (0)88 570 70 70
        email: infoservice@cbs.nl
        url: https://cbs.nl/
        role: pointOfContact

resources:
    nl-municipalities:
        type: collection
        title: Dutch Municipalities
        description: CBS Municipalities of The Netherlands, 2025 (generalized)
        keywords:
          - Netherlands
          - CBS
          - Municipalities
          - Regions
          - Statistical Areas
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.cbs.nl/nl-nl/dossier/nederland-regionaal/geografische-data/cbs-gebiedsindelingen
        extents:
            spatial:
                bbox: [2.5, 50.5, 7.5, 53.75]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2025-01-01T00:00:00Z
                end: null
        providers:
            - type: feature
              name: GeoJSON
              data: data/pdok_cbs_municipalities_nl_2025.json
              id_field: id
              title_field: statnaam
              key_fields:
                - name: jaarcode
                - name: statcode
                  default: true
                - name: jrstatcode
