# Ansible workflow for single service deployment.
# Uses: https://github.com/dawidd6/action-ansible-playbook
# Options: https://github.com/dawidd6/action-ansible-playbook/blob/master/main.js
# Author: Just van den Broecke - 2021
#
name: pygeoapi Deploy ⚙️

# Trigger only when services/pygeoapi subdir changed
on:
  push:
    paths:
      - 'services/pygeoapi/**'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout ✅
      uses: actions/checkout@v2

    - name: Prepare pygeoapi Joins build
      run: |
        cd services/pygeoapi
        chmod +x clone_joins.sh
        ./clone_joins.sh

    - name: Run playbook ⚙
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
        directory: ./ansible
        key: ${{secrets.ANSIBLE_SSH_PRIVATE_KEY}}
        inventory: ${{secrets.ANSIBLE_INVENTORY_PROD}}
        vault_password: ${{secrets.ANSIBLE_VAULT_PASSWORD}}
        options: |
          --tags pygeoapi
          --verbose
